#!/bin/bash

check_deps(){
	deps=("sqlite3" "jq" "ncat")

	for dep in "${deps[@]}"; do 
		if ! command -v "$dep" >/dev/null; then
			echo "missing \"$dep\", cannot continue" >&2;
			exit 2
		fi
	done
}

main(){
	if [ -z "$1" -o ! -e "$1" ]; then
		echo "missing or non-existent config file!!!" >&2
		exit 1
	fi

	if [[ "$(file --mime-type "$1")" != *application/json ]]; then
		echo "liar! \"$1\" is not json!"
		exit 1
	fi
	
	callback="$(jq -r ".callback" < "$1")"
	if [ -z "$callback" -o ! -e "$callback" ]; then
		echo "whereis my callback script?!"
		exit 1
	fi
	
	if [[ "$(file --mime-type "$callback")" != *text/x-shellscript ]]; then
		echo "liar! \"$callback\" is not a shell script!"
		exit 1
	fi
	
	db="$(jq -r ".db_path" < "$1")"
	port="$(jq -r ".port" < "$1")"
	addr="$(jq -r ".addr" < "$1")"

	export REP_DATABASE="$db"

	exec $(command -v ncat) -l $port -k --sh-exec $(readlink -f $callback) 
}

main $*
